functional:
  - Просмотр товаров с фильтрацией и постраничным выводом.
  - Добавление товаров в корзину.
  - Оформление заказа с переходом на страницу оплаты.
non-functional:
  - Адаптивная верстка для мобильных устройств.
  - Безопасность и защита данных пользователя.
  - Совместимость с последними версиями браузеров.
  - Возможность обработки большого трафика.
implicit:
  - Удобный и интуитивно понятный интерфейс.
  - Поддержка различных устройств и браузеров.
  - Быстрая загрузка страниц.
  - Корректное отображение цен и скидок.
